apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: python-sql-demo
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS studentdb;
    USE studentdb;
    CREATE TABLE IF NOT EXISTS students (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(50),
      email VARCHAR(100)
    );
    INSERT INTO students (name, email)
    VALUES ('Alice', 'alice@example.com'),
           ('Bob', 'bob@example.com');
