apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-sql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: vighneshsikati77/python-sql-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql-service.python-sql-demo.svc.cluster.local
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
