apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: python-sql-demo
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-sql-demo
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
